### ISSUE TITLE
Windows specific

### ISSUE THREAD

**Issue by istadem2077** [suleymanovdev/cppchess#9]
Impossible to compile in Unix environment because of certain inclusions. Please make it portable.

**Comment by suleymanovdev** [comment]
You know, I gonna create new release with code for Linux operating system. It take 4 days (min). 👨‍💻

**Comment by istadem2077** [comment]
It shouldn't different for Linux separately, it should compile for/on both Windows and GNU/Linux operating systems. Such application shouldn't be OS-specific, after all it's not network driver or whatever.

**Comment by suleymanovdev** [comment]
I understand everything will be gradual, but until people decide on the OS, we have to do it individually or all together with extra functionality, which I'm going to do within 5 days. 🐦
